-- Insert categories
INSERT INTO Category (id, description, name) VALUES
                                                 (NEXTVAL('category_seq'), 'Electronics and gadgets', 'Electronics'),
                                                 (NEXTVAL('category_seq'), 'Home and kitchen appliances', 'Home & Kitchen'),
                                                 (NEXTVAL('category_seq'), 'Clothing and fashion', 'Fashion'),
                                                 (NEXTVAL('category_seq'), 'Books and stationery', 'Books'),
                                                 (NEXTVAL('category_seq'), 'Fitness and sports equipment', 'Fitness & Sports');

-- Insert products
INSERT INTO Product (id, name, description, available_quantity, price, category_id) VALUES
                                                                                        (NEXTVAL('product_seq'), 'Smartphone', 'Latest model smartphone', 100, 699.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Laptop', 'High performance laptop', 50, 999.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Tablet', '10-inch display tablet', 200, 399.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Smartwatch', 'Fitness tracker smartwatch', 150, 199.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Blender', 'High-speed blender', 75, 89.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Air Fryer', 'Healthy cooking air fryer', 60, 129.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Vacuum Cleaner', 'Robotic vacuum cleaner', 40, 299.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Microwave Oven', '700W microwave oven', 30, 79.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Jeans', 'Comfortable denim jeans', 120, 49.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'T-shirt', 'Cotton t-shirt', 200, 19.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Jacket', 'Winter jacket', 80, 99.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Sneakers', 'Running sneakers', 140, 59.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Notebook', 'Hardcover notebook', 300, 4.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Pen', 'Ballpoint pen', 500, 1.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Textbook', 'Science textbook', 70, 39.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Yoga Mat', 'Non-slip yoga mat', 150, 24.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Dumbbells', 'Set of 2 dumbbells', 90, 49.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Treadmill', 'Electric treadmill', 20, 499.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Football', 'Official size football', 120, 29.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Basketball', 'Indoor/outdoor basketball', 100, 19.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Smart TV', '4K Ultra HD Smart TV', 60, 799.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Headphones', 'Noise-cancelling headphones', 150, 129.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Bluetooth Speaker', 'Portable Bluetooth speaker', 200, 49.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Coffee Maker', 'Automatic coffee maker', 70, 69.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Toaster', '4-slice toaster', 80, 34.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Slow Cooker', '6-quart slow cooker', 60, 59.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Dress', 'Summer dress', 110, 39.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Sweater', 'Wool sweater', 90, 49.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Boots', 'Leather boots', 70, 89.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Novel', 'Bestselling novel', 150, 14.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Magazine', 'Monthly magazine', 200, 5.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Fitness Tracker', 'Wearable fitness tracker', 100, 99.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Resistance Bands', 'Set of resistance bands', 130, 19.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Elliptical Trainer', 'Elliptical exercise machine', 20, 699.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Smart Light Bulbs', 'Wi-Fi enabled smart light bulbs', 300, 29.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Gaming Console', 'Next-gen gaming console', 50, 499.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Air Conditioner', 'Portable air conditioner', 30, 399.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Ceiling Fan', 'Energy-efficient ceiling fan', 50, 129.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Iron', 'Steam iron', 90, 29.99, (SELECT id FROM Category WHERE name = 'Home & Kitchen')),
                                                                                        (NEXTVAL('product_seq'), 'Scarf', 'Winter scarf', 120, 19.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Hat', 'Summer hat', 100, 14.99, (SELECT id FROM Category WHERE name = 'Fashion')),
                                                                                        (NEXTVAL('product_seq'), 'Cookbook', 'Gourmet recipes cookbook', 80, 24.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Marker Set', 'Color marker set', 200, 9.99, (SELECT id FROM Category WHERE name = 'Books')),
                                                                                        (NEXTVAL('product_seq'), 'Jump Rope', 'Adjustable jump rope', 140, 14.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Kettlebell', '20 lb kettlebell', 60, 34.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Yoga Block', 'Foam yoga block', 110, 9.99, (SELECT id FROM Category WHERE name = 'Fitness & Sports')),
                                                                                        (NEXTVAL('product_seq'), 'Wireless Charger', 'Fast wireless charger', 200, 24.99, (SELECT id FROM Category WHERE name = 'Electronics')),
                                                                                        (NEXTVAL('product_seq'), 'Camera', 'Digital camera', 40, 399.99, (SELECT id FROM Category WHERE name = 'Electronics'));
